### PR TITLE
Updated to null safety

### PR DESCRIPTION
**Pull request by larryaasen**
Thanks for creating this very useful package. This PR is to update this package to null safety.

### CODE REVIEW

**Comment by larryaasen** [comment]
The GitHub checks failed because it is not using the beta branch, and I don't have access to change the dart.yml file because: (refusing to allow an OAuth App to create or update workflow `.github/workflows/dart.yml` without `workflow` scope).

**Comment by larryaasen** [comment]
This PR should fix issue https://github.com/dartninja/version/issues/5

**Comment by larryaasen** [comment]
@sanmadjack Is there anything more I can do for this PR?

**Comment by sanmadjack** [comment]
I'm reviewing this now.

**Comment by sanmadjack** [comment]
Did you use the migration tool to do this?

**Comment by larryaasen** [comment]
Yes I did.

**Comment by sanmadjack** [comment]
Okay. I couldn't accept the PR as is, since the decisions made with the migration tool weren't correct for this library. This library has always enforced inputs not being null, so the only code changes that were needed were to update the SDK version requirement and stop checking for nulls, since they now can no longer be null. The user supplying null values for version numbers isn't an issue for this library to solve, so it will continue to enforce no nulls being provided. The new version will is available by depending on ^2.0.0-0. Once the new null safety changes go to stable I'll push out a stable 2.0.0.

**Comment by sanmadjack** [comment]
To be clear, I did cherry pick your commit, then adjusted it to make the properties non-nullable.

**Pull request closed without merging**
